FROM node:carbon
 
WORKDIR /usr/src/app
 
# Install app dependencies

COPY package*.json .
 
# Install any needed packages
RUN npm i
 
# Bundle app source
COPY . .
 
EXPOSE 4200
 
CMD [ "npm", "start" ]